const LOGIN = 'LOGIN';
const LOGOUT = 'LOGOUT';
const LOGIN_PENDING  = "LOGIN_PENDING";
const TOKEN = "TOKEN";
const REDIRECTED_AS_UNREGISTERED = "REDIRECTED_AS_UNREGISTERED"
const PROMISE = "PROMISE";
const PENDING = "PENDING";
const RESOLVED = "RESOLVED";
const REJECTED = "REJECTED";
const PASS_REQUEST_DATA = "PASS_REQUEST_DATA"

export {
    LOGIN,
    LOGOUT,
    LOGIN_PENDING,
    TOKEN,
    REDIRECTED_AS_UNREGISTERED,
    PROMISE,
    PENDING,
    RESOLVED,
    REJECTED,
    PASS_REQUEST_DATA,

}